# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'docker-integration'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud-new'
    organization: 'ankitkumar03'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner,
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=ankitkumar03_demo1
      sonar.projectName=demo1
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package sonar:sonar'
    sonarQubeRunAnalysis: True
    sqMavenPluginVersionChoice: 'latest'


- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifactName: 'first' 
    publishLocation: 'pipeline'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'demo'
    azureContainerRegistry: '{"loginServer":"azuredevops89.azurecr.io", "id" : "/subscriptions/e25c0a93-619e-4b0f-8713-ada2c8e89425/resourceGroups/ankitkumar03/providers/Microsoft.ContainerRegistry/registries/azuredevops89"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'

